[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "docs"
version = "0.1.0"
description = "Documentation generation tools"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]