[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "axiom"
version = "0.1.0"
description = "Clean CLI code assistant with coherent tools"
dependencies = []

[project.optional-dependencies]
dev = ["pytest", "ruff"]